name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install coverage
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run --source='.' manage.py test
          coverage report -m

      - name: Calculate coverage percentage
        id: coverage
        run: |
          COVERAGE=$(coverage report -m | grep -oP '\d+\.\d+(?=%)' | head -1)
          echo "::set-output name=coverage::$COVERAGE"

      - name: Check coverage threshold
        run: |
          COVERAGE_THRESHOLD=80.0
          CURRENT_COVERAGE=$(echo "${{ steps.coverage.outputs.coverage }}")
          if (( $(awk 'BEGIN {print ("'$CURRENT_COVERAGE'" >= "'$COVERAGE_THRESHOLD'")}') )); then
            echo "Coverage is ${CURRENT_COVERAGE}% which meets the threshold of ${COVERAGE_THRESHOLD}%"
          else
            echo "Coverage is ${CURRENT_COVERAGE}% which does not meet the threshold of ${COVERAGE_THRESHOLD}%"
            exit 1
          fi

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
