name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install coverage.py
        run: pip install coverage

      - name: Run tests with coverage and generate report
        run: |
          coverage run --source=. manage.py test
          coverage xml -o coverage.xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # Especificar la ubicación del informe de cobertur
          SONAR_COVERAGE_REPORT_PATH: ./coverage.xml
